//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commons.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActivityServiceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityServiceMessage() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commons.Resources.ActivityServiceMessage", typeof(ActivityServiceMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune activité trouvée pour cet ID..
        /// </summary>
        public static string ActivityServiceStatus_ActivityNotFound_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_ActivityNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de l&apos;ajout d&apos;un participant à l&apos;activité..
        /// </summary>
        public static string ActivityServiceStatus_ErrorWhenAddingAttendee_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_ErrorWhenAddingAttendee_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ActivityServiceStatus_ErrorWhenAddingFile_Message.
        /// </summary>
        public static string ActivityServiceStatus_ErrorWhenAddingFile_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_ErrorWhenAddingFile_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la suppression d&apos;un ou plusieurs fichiers médias de l&apos;activité..
        /// </summary>
        public static string ActivityServiceStatus_ErrorWhenRemovingFile_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_ErrorWhenRemovingFile_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Participant est invalide.
        /// </summary>
        public static string ActivityServiceStatus_FollowerInvalid_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_FollowerInvalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Données de l&apos;activité invalides..
        /// </summary>
        public static string ActivityServiceStatus_InvalidActivity_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_InvalidActivity_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du mapping des données de l&apos;activité..
        /// </summary>
        public static string ActivityServiceStatus_MappingError_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_MappingError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun média fourni pour l&apos;activité..
        /// </summary>
        public static string ActivityServiceStatus_NoMedia_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_NoMedia_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de l&apos;enregistrement d&apos;un ou plusieurs fichiers médias de l&apos;activité.
        ///.
        /// </summary>
        public static string ActivityServiceStatus_PersistenceError_Message {
            get {
                return ResourceManager.GetString("ActivityServiceStatus_PersistenceError_Message", resourceCulture);
            }
        }
    }
}
