//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commons.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TravelServiceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TravelServiceMessage() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commons.Resources.TravelServiceMessage", typeof(TravelServiceMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Impossible de cloner le voyage..
        /// </summary>
        public static string CLONE_FAILED {
            get {
                return ResourceManager.GetString("CLONE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de la sauvegarde en base..
        /// </summary>
        public static string DATABASE_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur inattendue, les fichiers n&apos;ont pas été ajoutés correctement..
        /// </summary>
        public static string ERROR_WHEN_ADDING_FILE {
            get {
                return ResourceManager.GetString("ERROR_WHEN_ADDING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur inattendue, les souvenirs n&apos;ont pas été supprimés correctement..
        /// </summary>
        public static string ERROR_WHEN_REMOVING_FILE {
            get {
                return ResourceManager.GetString("ERROR_WHEN_REMOVING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le souvenir n&apos;existe pas .
        /// </summary>
        public static string INVALID_MEMORY {
            get {
                return ResourceManager.GetString("INVALID_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Les données du voyage sont manquantes ou invalides..
        /// </summary>
        public static string INVALID_TRAVEL {
            get {
                return ResourceManager.GetString("INVALID_TRAVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  L’identifiant du voyage est invalide..
        /// </summary>
        public static string INVALID_TRAVEL_ID {
            get {
                return ResourceManager.GetString("INVALID_TRAVEL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souvenir pas trouvé.
        /// </summary>
        public static string MEDIA_NOT_FOUND {
            get {
                return ResourceManager.GetString("MEDIA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de média à ajouter !.
        /// </summary>
        public static string NO_MEDIA {
            get {
                return ResourceManager.GetString("NO_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération réussie..
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voyage ajouté avec succès.
        /// </summary>
        public static string TRAVEL_ADDED {
            get {
                return ResourceManager.GetString("TRAVEL_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Aucun voyage trouvé avec cet ID..
        /// </summary>
        public static string TRAVEL_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRAVEL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voyage supprimé avec succès.
        /// </summary>
        public static string TRAVEL_REMOVED {
            get {
                return ResourceManager.GetString("TRAVEL_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur inattendue, contactez le support.
        ///.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
