//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.MAUI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogsStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.MAUI.Resources.Localization.DialogsStrings", typeof(DialogsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        internal static string CommonsNo {
            get {
                return ResourceManager.GetString("CommonsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        internal static string CommonsYes {
            get {
                return ResourceManager.GetString("CommonsYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Voulez-vous vraiment supprimer cette activité  
        ///Cette activité contient :
        /// - {0} participant(s)
        /// - {1} facture(s)
        /// Tous ces éléments seront également supprimés de façon définitive..
        /// </summary>
        internal static string DeleteActivity_Confirmation {
            get {
                return ResourceManager.GetString("DeleteActivity_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string DeleteActivity_NOK {
            get {
                return ResourceManager.GetString("DeleteActivity_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui, supprimer.
        /// </summary>
        internal static string DeleteActivity_OK {
            get {
                return ResourceManager.GetString("DeleteActivity_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation de suppression.
        /// </summary>
        internal static string DeleteActivity_Title {
            get {
                return ResourceManager.GetString("DeleteActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer cette dépense ?
        ///Cette dépense contient :
        /// - {0} ticket(s)                                    
        ///Tous ces éléments seront également supprimés de façon définitive..
        /// </summary>
        internal static string DeleteExpense_Confirmation {
            get {
                return ResourceManager.GetString("DeleteExpense_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string DeleteExpense_NOK {
            get {
                return ResourceManager.GetString("DeleteExpense_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui, supprimer.
        /// </summary>
        internal static string DeleteExpense_OK {
            get {
                return ResourceManager.GetString("DeleteExpense_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation de suppression.
        /// </summary>
        internal static string DeleteExpense_Title {
            get {
                return ResourceManager.GetString("DeleteExpense_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer {0} souvenir(s) ?.
        /// </summary>
        internal static string DeleteMemories_Confirmation {
            get {
                return ResourceManager.GetString("DeleteMemories_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string DeleteMemories_Title {
            get {
                return ResourceManager.GetString("DeleteMemories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Voulez-vous vraiment supprimer le voyage ?.
        /// </summary>
        internal static string DeleteTravel_Confirmation {
            get {
                return ResourceManager.GetString("DeleteTravel_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        internal static string DeleteTravel_No {
            get {
                return ResourceManager.GetString("DeleteTravel_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string DeleteTravel_Title {
            get {
                return ResourceManager.GetString("DeleteTravel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        internal static string DeleteTravel_Yes {
            get {
                return ResourceManager.GetString("DeleteTravel_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez des changements non enregistrés. Voulez-vous les enregistrer avant de quitter ?.
        /// </summary>
        internal static string WIP_Confirmation {
            get {
                return ResourceManager.GetString("WIP_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter sans enregistrer.
        /// </summary>
        internal static string WIP_NOK {
            get {
                return ResourceManager.GetString("WIP_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        internal static string WIP_OK {
            get {
                return ResourceManager.GetString("WIP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifications en attente.
        /// </summary>
        internal static string WIP_Title {
            get {
                return ResourceManager.GetString("WIP_Title", resourceCulture);
            }
        }
    }
}
