<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exception\**" />
    <Compile Remove="LogService\**" />
    <Compile Remove="Utilities\**" />
    <EmbeddedResource Remove="Exception\**" />
    <EmbeddedResource Remove="LogService\**" />
    <EmbeddedResource Remove="Utilities\**" />
    <None Remove="Exception\**" />
    <None Remove="LogService\**" />
    <None Remove="Utilities\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum" Version="8.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\ActivityServiceMessage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ActivityServiceMessage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ExpenseServiceMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ExpenseServiceMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\GlobalServiceMessage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GlobalServiceMessage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\LogBookServiceMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LogBookServiceMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MediaServiceMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MediaServiceMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\TravelServiceMessage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TravelServiceMessage.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ActivityServiceMessage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ActivityServiceMessage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ExpenseServiceMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ExpenseServiceMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\GlobalServiceMessage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>GlobalServiceMessage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\LogBookServiceMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LogBookServiceMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MediaServiceMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MediaServiceMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TravelServiceMessage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>TravelServiceMessage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
